#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    non_snake_case
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`.

use crate::api::*;
use flutter_rust_bridge::*;

// Section: imports

// Section: wire functions

#[no_mangle]
pub extern "C" fn wire_node_handle(port_: i64, cmd_key: *mut wire_uint_8_list) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "node_handle",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_cmd_key = cmd_key.wire2api();
            move |task_callback| Ok(node_handle(api_cmd_key))
        },
    )
}

#[no_mangle]
pub extern "C" fn wire_publish_message(port_: i64, data: *mut wire_OptionTwist) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "publish_message",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_data = data.wire2api();
            move |task_callback| Ok(publish_message(api_data))
        },
    )
}

#[no_mangle]
pub extern "C" fn wire_shutdown(port_: i64) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "shutdown",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| Ok(shutdown()),
    )
}

// Section: wire structs

#[repr(C)]
#[derive(Clone)]
pub struct wire_OptionTwist {
    linear: *mut wire_Vec3,
    angular: *mut wire_Vec3,
}

#[repr(C)]
#[derive(Clone)]
pub struct wire_uint_8_list {
    ptr: *mut u8,
    len: i32,
}

#[repr(C)]
#[derive(Clone)]
pub struct wire_Vec3 {
    x: f64,
    y: f64,
    z: f64,
}

// Section: wrapper structs

// Section: static checks

// Section: allocate functions

#[no_mangle]
pub extern "C" fn new_box_autoadd_option_twist() -> *mut wire_OptionTwist {
    support::new_leak_box_ptr(wire_OptionTwist::new_with_null_ptr())
}

#[no_mangle]
pub extern "C" fn new_box_autoadd_vec_3() -> *mut wire_Vec3 {
    support::new_leak_box_ptr(wire_Vec3::new_with_null_ptr())
}

#[no_mangle]
pub extern "C" fn new_uint_8_list(len: i32) -> *mut wire_uint_8_list {
    let ans = wire_uint_8_list {
        ptr: support::new_leak_vec_ptr(Default::default(), len),
        len,
    };
    support::new_leak_box_ptr(ans)
}

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        if self.is_null() {
            None
        } else {
            Some(self.wire2api())
        }
    }
}

impl Wire2Api<String> for *mut wire_uint_8_list {
    fn wire2api(self) -> String {
        let vec: Vec<u8> = self.wire2api();
        String::from_utf8_lossy(&vec).into_owned()
    }
}

impl Wire2Api<OptionTwist> for *mut wire_OptionTwist {
    fn wire2api(self) -> OptionTwist {
        let wrap = unsafe { support::box_from_leak_ptr(self) };
        (*wrap).wire2api().into()
    }
}

impl Wire2Api<Vec3> for *mut wire_Vec3 {
    fn wire2api(self) -> Vec3 {
        let wrap = unsafe { support::box_from_leak_ptr(self) };
        (*wrap).wire2api().into()
    }
}

impl Wire2Api<f64> for f64 {
    fn wire2api(self) -> f64 {
        self
    }
}

impl Wire2Api<OptionTwist> for wire_OptionTwist {
    fn wire2api(self) -> OptionTwist {
        OptionTwist {
            linear: self.linear.wire2api(),
            angular: self.angular.wire2api(),
        }
    }
}

impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

impl Wire2Api<Vec<u8>> for *mut wire_uint_8_list {
    fn wire2api(self) -> Vec<u8> {
        unsafe {
            let wrap = support::box_from_leak_ptr(self);
            support::vec_from_leak_ptr(wrap.ptr, wrap.len)
        }
    }
}

impl Wire2Api<Vec3> for wire_Vec3 {
    fn wire2api(self) -> Vec3 {
        Vec3 {
            x: self.x.wire2api(),
            y: self.y.wire2api(),
            z: self.z.wire2api(),
        }
    }
}

// Section: impl NewWithNullPtr

pub trait NewWithNullPtr {
    fn new_with_null_ptr() -> Self;
}

impl<T> NewWithNullPtr for *mut T {
    fn new_with_null_ptr() -> Self {
        std::ptr::null_mut()
    }
}

impl NewWithNullPtr for wire_OptionTwist {
    fn new_with_null_ptr() -> Self {
        Self {
            linear: core::ptr::null_mut(),
            angular: core::ptr::null_mut(),
        }
    }
}

impl NewWithNullPtr for wire_Vec3 {
    fn new_with_null_ptr() -> Self {
        Self {
            x: Default::default(),
            y: Default::default(),
            z: Default::default(),
        }
    }
}

// Section: impl IntoDart

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

// Section: sync execution mode utility

#[no_mangle]
pub extern "C" fn free_WireSyncReturnStruct(val: support::WireSyncReturnStruct) {
    unsafe {
        let _ = support::vec_from_leak_ptr(val.ptr, val.len);
    }
}
