// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.49.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names

import "bridge_definitions.dart";
import 'dart:convert';
import 'dart:async';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'bridge_generated.io.dart'
    if (dart.library.html) 'bridge_generated.web.dart';
import 'package:meta/meta.dart';

class RobotNodeImpl implements RobotNode {
  final RobotNodePlatform _platform;
  factory RobotNodeImpl(ExternalLibrary dylib) =>
      RobotNodeImpl.raw(RobotNodePlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory RobotNodeImpl.wasm(FutureOr<WasmModule> module) =>
      RobotNodeImpl(module as ExternalLibrary);
  RobotNodeImpl.raw(this._platform);
  Future<void> nodeHandle({required String url, dynamic hint}) =>
      _platform.executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => _platform.inner
            .wire_node_handle(port_, _platform.api2wire_String(url)),
        parseSuccessData: _wire2api_unit,
        constMeta: kNodeHandleConstMeta,
        argValues: [url],
        hint: hint,
      ));

  FlutterRustBridgeTaskConstMeta get kNodeHandleConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "node_handle",
        argNames: ["url"],
      );

  Future<Uint8List?> generateTwist(
          {required String topic,
          required double x,
          required double z,
          dynamic hint}) =>
      _platform.executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => _platform.inner.wire_generate_twist(port_,
            _platform.api2wire_String(topic), api2wire_f64(x), api2wire_f64(z)),
        parseSuccessData: _wire2api_opt_ZeroCopyBuffer_Uint8List,
        constMeta: kGenerateTwistConstMeta,
        argValues: [topic, x, z],
        hint: hint,
      ));

  FlutterRustBridgeTaskConstMeta get kGenerateTwistConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "generate_twist",
        argNames: ["topic", "x", "z"],
      );

// Section: wire2api

  Uint8List _wire2api_ZeroCopyBuffer_Uint8List(dynamic raw) {
    return raw as Uint8List;
  }

  Uint8List? _wire2api_opt_ZeroCopyBuffer_Uint8List(dynamic raw) {
    return raw == null ? null : _wire2api_ZeroCopyBuffer_Uint8List(raw);
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }

  void _wire2api_unit(dynamic raw) {
    return;
  }
}

// Section: api2wire

@protected
double api2wire_f64(double raw) {
  return raw;
}

@protected
int api2wire_u8(int raw) {
  return raw;
}
